#!/bin/sh -e

# $Id: bootstrap,v 1.12 2009-09-26 02:20:55 joostvb Exp $

# bootstrap - script to bootstrap the distribution rolling engine

# This script is free software; you can distribute it and/or modify it
# under the terms of the GNU GPL.  See the file COPYING.

# usage:
# ./bootstrap && ./configure && make distcheck
#
# this yields a tarball (and a .tar.bz2 too) which one can install doing
#
# $ tar zxf PACKAGENAME-*.tar.gz
# $ cd PACKAGENAME-*
# $ ./configure
# $ make
# # make install

# requirements:
#  GNU autoconf, from e.g. ftp.gnu.org:/pub/gnu/autoconf/
#  GNU automake, from e.g. ftp.cygnus.com:/pub/tromey/
#  cvs2cl, from http://www.red-bean.com/cvs2cl/ (see Makefile.am)

set -x

test -f ChangeLog || {
    # http://josefsson.org/git2cl/
    # we want no unprotected emailadresses in the cl
    git log --pretty --numstat --summary | sed 's/<[^>][^>]*>//g' | \
      git2cl > ChangeLog
    # touch ChangeLog && cvs2cl --prune
}

test -f VERSION.m4 || ./setversion

AUTOMAKE=automake-1.11 ACLOCAL=aclocal-1.11 autoreconf --install --symlink

