#!/bin/sh -e

# $Id: bootstrap,v 1.9 2004-07-21 14:36:05 joostvb Exp $

# bootstrap - script to bootstrap the distribution rolling engine

# This script is free software; you can distribute it and/or modify it
# under the terms of the GNU GPL.  See the file COPYING.

# usage:
# ./bootstrap && ./configure && make distcheck
#
# this yields a tarball (and a .tar.bz2 too) which one can install doing
#
# $ tar zxf PACKAGENAME-*.tar.gz
# $ cd PACKAGENAME-*
# $ ./configure
# $ make
# # make install

# requirements:
#  GNU autoconf, from e.g. ftp.gnu.org:/pub/gnu/autoconf/
#  GNU automake, from e.g. ftp.cygnus.com:/pub/tromey/
#  cvs2cl, from http://www.red-bean.com/cvs2cl/ (see Makefile.am)

# The build system is known to work with aclocal and automake 1.8.5.

set -x

test -f ChangeLog || {
    touch ChangeLog && cvs2cl --prune
}

test -f VERSION.m4 || ./setversion

# If you have pkg-config 0.15.0-4 installed, and use aclocal >= 1.8, you'll
# get see a bug in /usr/share/aclocal/pkg.m4 , see
# http://bugs.debian.org/221818 for the bugreport (and a patch)
# This bug makes aclocal whine, but is not effectively harming us.

aclocal \
    && automake --add-missing --gnu --verbose --warnings=all \
    && autoconf

