#!/bin/sh -e

# this file maintained at http://git.mdcc.cx/uruk.git

# bootstrap - script to bootstrap the distribution rolling engine

# usage:
# ./bootstrap && ./configure && make distcheck
#
# this yields a tarball which one can install doing
#
# $ tar zxf PACKAGENAME-*.tar.gz
# $ cd PACKAGENAME-*
# $ ./configure
# $ make
# # make install

# requirements:
#  GNU autoconf, from e.g. ftp.gnu.org:/pub/gnu/autoconf/autoconf-2.50.tar.gz
#  GNU automake, from e.g. ftp.cygnus.com:/pub/tromey
#  git2cl, from e.g. http://josefsson.org/git2cl/, and git

set -x

test -f ChangeLog || {
    # we want no unprotected emailadresses in the cl
    git log --pretty --numstat --summary | sed 's/<[^>][^>]*>//g' | \
      git2cl >ChangeLog
}

test -f VERSION.m4 || ./setversion

test -f acinclude.m4 || {
    if test -f /usr/share/aclocal/ac_define_dir.m4
    then
        ln -s /usr/share/aclocal/ac_define_dir.m4 acinclude.m4
    else
        cat <<EOT
You need the autoconf-archive Debian package, version >= 20031029-1.
Alternatively, you could install the GNU Autoconf Macro Archive's
http://autoconf-archive.cryp.to/ac_define_dir.m4 as acinclude.m4.
EOT
   fi
}


# Override automake 1.9 default: automake1.9 version 1.9.6+nogfdl-3
# creates symlink to /usr/share/automake-1.9/COPYING which is GPL v2.
# We want v3.
test -f COPYING || {
    ln -s /usr/share/common-licenses/GPL-3 COPYING
}

AUTOMAKE=automake-1.11 ACLOCAL=aclocal-1.11 autoreconf --install \
      --symlink --make

# aclocal \
#    && automake --add-missing --verbose --gnu \
#    && autoconf


