#!/bin/sh -e

# this file maintained using arch at http://arch.gna.org/uruk/

# bootstrap - script to bootstrap the distribution rolling engine

# usage:
# ./bootstrap && ./configure && make distcheck
#
# this yields a tarball which one can install doing
#
# $ tar zxf PACKAGENAME-*.tar.gz
# $ cd PACKAGENAME-*
# $ ./configure
# $ make
# # make install

# requirements:
#  GNU autoconf, from e.g. ftp.gnu.org:/pub/gnu/autoconf/autoconf-2.50.tar.gz
#  GNU automake, from e.g. ftp.cygnus.com:/pub/tromey
#  GNU arch, from e.g. http://regexps.srparish.net/www/

set -x

test -f ChangeLog || {
    tla changelog > ChangeLog
}

test -f VERSION.m4 || ./setversion

test -f acinclude.m4 || {
    if test -f /usr/share/autoconf-archive/ac_define_dir.m4
    then
        ln -s /usr/share/autoconf-archive/ac_define_dir.m4 acinclude.m4
    else
        cat <<EOT
You need the autoconf-archive Debian package, version >= 20031029-1.
Alternatively, you could please install the GNU Autoconf Macro Archive's
http://autoconf-archive.cryp.to/ac_define_dir.m4 as acinclude.m4.
EOT
   fi
}

aclocal \
    && automake --add-missing --verbose --gnu \
    && autoconf


