
Date: Tue, 13 Dec 2011 14:22:26 +0100
From: Joost van Baal-Ilić <joostvb@uvt.nl>
To: Suresh Krishnan <suresh.krishnan@ericsson.com>
Subject: script for icmpv6 firewall rules, rfc 4890, software license
Message-ID: <20111213132226.GY10269@dijkstra.uvt.nl>

Hello Suresh Krishnan,

Would you be willing to release your example script to configure icmpv6
firewall rules as published in rfc 4890 under the 2-clause BSD license?

I am maintaining a firewall script[1], which is shipped[2] with Debian
GNU/Linux and Ubuntu.  I am working on improving the script when dealing with
IPv6 traffic, and would like to use your very useful script as published in RFC
4890[3].  Of course, I'll give proper attribution--as required by Open Source
licenses[4].

Furthermore, I believe it's not just me or my firewall script, but also others
and other firewall scripts who could benefit from your script.  Releasing it
under an Open Source license makes the script more accesible for usage.  It
would contribute to the development of the internet.  The 2-clause BSD
license[5] is such an Open Source license; others will likely be fine too.

Replying to this message and stating: "I release the example script to
configure icmpv6 firewall rules as published in rfc 4890 under the 2-clause BSD
license" would suffice.

Thanks a lot for your work!

Kind regards,

Joost van Baal-Ilić


[1] http://mdcc.cx/uruk/
[2] http://packages.debian.org/uruk
[3] http://www.ietf.org/rfc/rfc4890.txt
[4] http://www.opensource.org/licenses/BSD-2-Clause

[5]
Copyright (c) 2006, Suresh Krishnan. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

-  Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

-  Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

--
Joost van Baal-Ilić                       http://abramowitz.uvt.nl/
                                                 Tilburg University
mailto:joostvb.uvt.nl                               The Netherlands

-----------------------------------------------------------------------------

Received: from poincare.uvt.nl (poincare.uvt.nl [137.56.247.172]) by
 dijkstra.uvt.nl (Postfix) with ESMTPS id 6D3531ACF0B for
 <joostvb@dijkstra.uvt.nl>; Tue, 13 Dec 2011 23:49:38 +0100 (CET)
Received: from localhost (localhost [127.0.0.1]) by poincare.uvt.nl
 (Postfix) with ESMTP id 53AD0280235 for <joostvb@dijkstra.uvt.nl>; Tue, 13
 Dec 2011 23:49:38 +0100 (CET)
X-Virus-Scanned: Debian amavisd-new at uvt.nl
Received: from poincare.uvt.nl ([127.0.0.1]) by localhost (poincare.uvt.nl
 [127.0.0.1]) (amavisd-new, port 10024) with ESMTP id pIsGjFS1IcEj for
 <joostvb@dijkstra.uvt.nl>; Tue, 13 Dec 2011 23:49:37 +0100 (CET)
Received: from imr4.ericy.com (imr4.ericy.com [198.24.6.9]) by
 poincare.uvt.nl (Postfix) with ESMTPS id A3381280231 for <joostvb@uvt.nl>;
 Tue, 13 Dec 2011 23:49:37 +0100 (CET)
Received: from eusaamw0707.eamcs.ericsson.se ([147.117.20.32]) by
 imr4.ericy.com (8.14.3/8.14.3/Debian-9.1ubuntu1) with ESMTP id
 pBDMgT1T009567 for <joostvb@uvt.nl>; Tue, 13 Dec 2011 16:42:43 -0600
Received: from [142.133.10.111] (147.117.20.214) by
 smtps-am.internal.ericsson.com (147.117.20.32) with Microsoft SMTP Server
 (TLS) id 8.3.137.0; Tue, 13 Dec 2011 17:42:27 -0500
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:7.0.1) Gecko/20110929
 Thunderbird/7.0.1
X-Enigmail-Version: 1.3.3
Message-ID: <4EE7D463.3030907@ericsson.com>
Date: Tue, 13 Dec 2011 17:40:35 -0500
From: Suresh Krishnan <suresh.krishnan@ericsson.com>
MIME-Version: 1.0
To: Joost van Baal-Ilić <joostvb@uvt.nl>
Subject: Re: script for icmpv6 firewall rules, rfc 4890, software license
References: <20111213132226.GY10269@dijkstra.uvt.nl>
In-Reply-To: <20111213132226.GY10269@dijkstra.uvt.nl>
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit


Hi Joost,
  I release the example script to configure icmpv6 firewall rules as
published in rfc 4890 under the 2-clause BSD license.

Thanks
Suresh

