#!/bin/sh

# LSB initscript functions, as defined in the LSB Spec 1.1.0
#
# Lawrence Lim <llim@redhat.com> - Tue, 26 June 2007
# Updated to the latest LSB 3.1 spec
# http://refspecs.freestandards.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic_lines.txt

# Modified by Joost van Baal-Ilić for uruk.

PATH=$PATH:/etc/redhat-lsb:/lib/uruk/lsb

start_daemon () {
        lsb_start_daemon "$@"
}

killproc () {
        lsb_killproc "$@"
}

pidofproc () {
        lsb_pidofproc "$@"
}

log_success_msg () {
        lsb_log_message success "$@"
}

log_failure_msg () {
        lsb_log_message failure "$@"
}

log_warning_msg () {
        lsb_log_message warning "$@"
}


