#!/bin/sh

# $Id: csp_sucp,v 1.1 2006-01-28 11:52:22 joostvb Exp $
# $Source: /cvsroot/caspar/caspar/caspar/script/csp_sucp,v $

# csp_sucp - mix scp with sudo
#
# example usage:
#  csp_sucp fstab rms@bilbo /etc

# first make sure our sudo-timestamp is fresh
ssh -T $2 sudo -v
# now run sudo: we won't be prompted for a password; and
# can use stdin for our data
exec ssh $2 "sudo sh -c \"cat - > $3/$1\"" < $1

